#' @title Rename columns with reserved names
#'
#' @description Column names that match a string listed in reserved_names are
#' given a postscript.
#'
#' @details This function is used to guard against overwriting existing columns
#' with information we have pulled from outside of the main table: If there is
#' a column with the same name as a reserved names it will be given a
#' postscript. For example, If there is a column in the raw data called
#' 'source', because 'source' is a column we add to all datasets,
#' our 'source' column in the raw data will become 'source_1'.
#'
#' @param dat dataframe.
#' @param reserved_names vector of character strings. Column names that we
#' don't want to exist yet in dat (e.g. if they are reserved for some other
#' future column).
#' @returns dat with offending columns given a numeric postscript to the name.
#' @examples
#' \dontrun{
#' dat <- data.frame("group" = c("Fox", "Bear"),
#'                   "value" = c("red", "black"),
#'                   "numeric" = 1:2)
#' newdat <- rename_reserved_colnames(dat, c("value", "source"))
#' }
#' @export
rename_reserved_colnames <- function(dat, reserved_names) {

  for (item in reserved_names) {
    if (item %in% names(dat)) {
      dat <- rename(dat, !!sym(paste0(item, "_1")) := !!sym(item))

      warning(
        "Existing '", item, "' column renamed as '", paste0(item, "_1"), "'. "
      )
    }
  }
  return(dat)
}


#' @title Rename columns using regular expressions to identify them
#'
#' @description Use regular expressions to identify which columns to rename,
#' and rename them.
#'
#' @details This renaming is controlled by the settings - if no columns require
#' renaming, the settings do not need to be supplied.
#'
#' @param dat dataframe
#' @param exclude_names character string. Any column names that should not be
#' included when looking for matches to the patterns. e.g. If data were
#' originally imported using xlsx_cells, you may want to exclude the column
#' names that are automatically generated by importing data with xlsx_cells.
#' @param patterns character string vector. One regular expression for each
#' column to be renamed. Must be given in the corresponding order to new_names.
#' In pub sec this variable is specified by columns_to_rename_patterns.
#' @param new_names  character string vector. One name for each column to be
#' renamed. Must be given in the corresponding order to patterns. In pub sec
#' this variable is specified by columns_to_rename_names.
#'
#' @returns dat with columns renamed
#'
#' @examples
#' \dontrun{
#' dat <- data.frame(
#'   data_type = "character",
#'   numeric = 1,
#'   Type = "A",
#'   Set = "B"
#'   )
#'  rename_columns(
#'      dat, exclude_names = c("data_type", "numeric"),
#'      patterns = c("(?i)type", "Set"),
#'      new_names = c("description_1", "description_2")
#'      )
#' }
#' @export
rename_columns <- function(dat, exclude_names, patterns, new_names){

  if (all(
    all(is.na(patterns)), all(is.na(new_names))
  )) {
    return (dat)
  } else if (any(
    all(is.na(patterns)), all(is.na(new_names))
  )) {
    stop(
      "At least one of columns_to_rename_patterns., columns_to_rename_names",
      "has not been supplied. If one is given, the others must also be ",
      "supplied in the settings."
    )
  } else {
    message ("Renaming columns based on settings.")
  }

  if (all(is.na(exclude_names))) {
    possibilities <- names(dat)
  } else {
    possibilities <- setdiff(names(dat), exclude_names)
  }

  with_renames <- dat

  for (i in 1:length(patterns)) {

    pattern <- patterns[i]
    new_name <- new_names[i]

    matches <- possibilities[str_detect(possibilities, pattern)]

    if (length(matches) > 1) {
      warning(
        "More than one column was matched to the pattern: '", pattern,
        "': '", paste0(matches, collapse = "', '"), "'. No column will be ",
        "given the name: '", new_name, "'. Please contact a developer to edit ",
        "the columns_to_rename_patterns setting."
      )
    } else if (length(matches) == 0) {
      warning(
        "No column names were matched to the pattern: '", pattern,
        "'. No column will be given the name: '", new_name, "'. Please ",
        "contact a developer to edit the columns_to_rename_patterns setting. ",
        "Developers: Check if the column in question been renamed via a ",
        "different method, e.g. if it is in col_with_row_headers_pattern, you ",
        "do not need to also specify it in columns_to_rename_patterns."
      )
    } else {

      with_renames <- with_renames %>%
        rename(!!sym(new_name) := !!sym(matches))

      message(
        "Column '", matches, "' renamed to '", new_name, "'."
      )
    }
  }

  return (with_renames)
}


#' @title Rename the value columns
#'
#' @description
#' Standardise column names so that the numeric column gets renamed 'value' and
#' the character column gets renamed 'non_numeric_value'.
#'
#' @details The non-numeric_value column will only be populated if there are
#' character values in a column that should be numeric in the raw data. For
#' example if 's' is used to indicate suppressed values in numeric columns,
#' it will end up in the non_numeric_value column.
#'
#' @param dat (tibble)
#'
#' @return dat with numeric column named 'value' and character column named
#' non_numeric_value if those columns exist
#'
#' @examples
#' \dontrun{
#' dat <- tibble(
#'   item = c("ball", "ball"),
#'   numeric = c(1, NA),
#'   character = c(NA, "Small sample size")
#' )
#' rename_value_columns(dat)
#' }
#' @export
rename_value_columns <- function(dat) {
  if ("numeric" %in% names(dat)) {
    message(
      "Renaming 'numeric' column as 'value'."
    )
      dat <-  rename(dat, value = numeric)
  }

  if ("character" %in% names(dat)) {
    message(
      "Renaming 'character' column as 'non_numeric_value'."
    )
    dat <- rename(dat, non_numeric_value = character)
  }

  return(dat)

}
