#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom digest digest
#' @importFrom dplyr across
#' @importFrom dplyr add_row
#' @importFrom dplyr all_of
#' @importFrom dplyr anti_join
#' @importFrom dplyr arrange
#' @importFrom dplyr between
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr count
#' @importFrom dplyr distinct
#' @importFrom dplyr ensym
#' @importFrom dplyr filter
#' @importFrom dplyr full_join
#' @importFrom dplyr group_by
#' @importFrom dplyr lag
#' @importFrom dplyr lead
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr right_join
#' @importFrom dplyr row_number
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr slice_tail
#' @importFrom dplyr summarise
#' @importFrom dplyr ungroup
#' @importFrom jsonlite fromJSON
#' @importFrom rlang :=
#' @importFrom rlang sym
#' @importFrom stringr fixed
#' @importFrom stringr str_count
#' @importFrom stringr str_detect
#' @importFrom stringr str_extract
#' @importFrom stringr str_extract_all
#' @importFrom stringr str_match
#' @importFrom stringr str_remove
#' @importFrom stringr str_remove_all
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_split
#' @importFrom stringr str_split_fixed
#' @importFrom stringr str_squish
#' @importFrom stringr str_starts
#' @importFrom stringr str_sub
#' @importFrom stringr str_to_lower
#' @importFrom stringr str_trim
#' @importFrom tibble is_tibble
#' @importFrom tibble tibble
#' @importFrom tidyr expand_grid
#' @importFrom tidyr fill
#' @importFrom tidyr unite
#' @importFrom tidyr unnest
#' @importFrom tidyxl xlsx_cells
#' @importFrom tidyxl xlsx_formats
#' @importFrom tidyxl xlsx_sheet_names
#' @importFrom unpivotr behead
#' @importFrom unpivotr spatter
## usethis namespace: end
NULL
