name: Test Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        install.packages('covr')
        install.packages('devtools')
        devtools::install_deps(dependencies = TRUE)

    - name: Run tests and coverage
      run: |
        Rscript -e 'covr::package_coverage(path = ".", type = "all", combine_types = FALSE, relative_path = TRUE, quiet = TRUE, clean = TRUE, line_exclusions = NULL, function_exclusions = NULL, pre_clean = TRUE, vignettes = FALSE)'
        Rscript -e 'covr::codecov()'

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
